### ISSUE TITLE
importing pyEDA.Device.PhysUnit error

### ISSUE THREAD

**Issue by johnjoo1** [cogenda/pyEDA#1]
When I tried to run diode.py, it gave me an error saying  importing pyEDA.Device.PhysUnit could not be found.  It turns out that Device package was not a part of the install.  

To correct this, 
1) I added "args.append("--add-package=pyEDA/Device")" to pydoctor file.
2) I added Device to the setup.py files so that it now reads "packages=['pyEDA', 'pyEDA.Circuit', 'pyEDA.Compact', 'pyEDA.FVMEqn', 'pyEDA.Mesh', 'pyEDA.PDE', 'pyEDA.Device'],)"
3) I added Device to the **init**.py file so that it now reads "**all**=['Circuit', 'Compact', 'FVMEqn', 'Mesh', 'PDE', 'Device']"

I have no idea if all of this is necessary, but it works now.

**Comment by cogenda** [comment]
Fixed. Thanks a lot!
